apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods.
  labels:
    name: wordpress-nginx
    role: nginx
  name: wordpress-nginx
  namespace: default
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: wordpress-nginx
    role: nginx
  sessionAffinity: None
  type: ClusterIP
