version: 2
## Example registry
# registries:
#   artifactory:
#     type: docker-registry
#     url: https://registry-1.docker.io/
#     token: ${{secrets.DOCKER_REMOTE_TOKEN}}

updates:
  # Maintain dependencies for nginx
  - package-ecosystem: "docker"
  directory: "/openshift/templates/images/nginx/docker/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 2
  reviewers:
    - bcgov/gdx-engagement-admin

  # Maintain dependencies for wordpress
  - package-ecosystem: "docker"
  directory: "/openshift/templates/images/wordpress/docker/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 2
  reviewers:
    - bcgov/gdx-engagement-admin

  # Maintain dependencies for mariadb
  - package-ecosystem: "docker"
  directory: "/openshift/templates/images/mariadb/docker/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 2
  reviewers:
    - bcgov/gdx-engagement-admin

  # Maintain dependencies for the sidecar
    - package-ecosystem: "docker"
  directory: "/openshift/templates/images/sidecar/docker/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 2
  reviewers:
    - bcgov/gdx-engagement-admin

  ## Example: Maintain dependencies for imagestreams using docker-remote
  # package-ecosystem: docker
  # directory: openshift/templates/dockerhub-imagestreams/alpine/docker/
  # registries:
  #   - artifactory
  # schedule:
  #   interval: daily
  # open-pull-requests-limit: 2
  # reviewers:
  #   - bcgov/gdx-engagement-admin
