version: "2.4"
# docker compose --env-file .env up --build site --force-recreate
networks:
  wp_deploy:
volumes:
  database:
  # Prevent anonymous volumes from accumulating.
  nginx_cache:
  nginx_run:
  db_run:

services:
  nginx:
    build:
      context: ../openshift/templates/images/nginx/docker
    ports:
      - 80:8080
      - 443:443
    links:
      - wordpress-php-fpm
    depends_on:
      - wordpress-php-fpm
      - db
    networks:
      - wp_deploy
    environment:
      APP_NAME: ${APP_NAME}
    volumes:
      - nginx_cache:/var/cache/nginx
      - nginx_run:/var/run
      - type: bind
        source: ../openshift/templates/images/nginx/docker/local-dev.conf
        target: /etc/nginx/conf.d/default.conf
      - ./certs/nginx/ssl:/etc/ssl/certs:ro
    volumes_from:
      - wordpress-php-fpm:rw
  db:
    build:
      context: ../openshift/templates/images/mariadb/docker
    logging:
      driver: none
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_run:/var/run
      - ${DB_VOLUME:-database}:/var/lib/mysql
    networks:
      - wp_deploy
    ports:
      - 3306:3306
  wordpress-php-fpm:
    user: www-data:www-data
    build:
      context: ../openshift/templates/images/wordpress/docker
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-1}
      WORDPRESS_ALLOW_MULTISITE: "1"
      WORDPRESS_MULTISITE: ${MULTISITE}
      WORDPRESS_SITE_ID_CURRENT_SITE: ${SITE_ID}
      WORDPRESS_DOMAIN_CURRENT_SITE: ${DOMAIN_CURRENT_SITE}
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define( 'WP_ALLOW_MULTISITE', true );
        define( 'MULTISITE', !!filter_var( getenv_docker( 'WORDPRESS_ALLOW_MULTISITE', '0' ), FILTER_VALIDATE_BOOLEAN ) );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', '${DOMAIN_CURRENT_SITE}' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', intval( getenv_docker( 'WORDPRESS_SITE_ID_CURRENT_SITE', '1' ) ) );
        define( 'BLOG_ID_CURRENT_SITE', intval( getenv_docker( 'WORDPRESS_SITE_ID_CURRENT_SITE', '1' ) ) );
        /* For Active Directory Integration on Multisite. */
        define( 'IS_WPMU', true );
        /* Other configs */
        define( 'WP_DEBUG_LOG', true );
    ports:
      - 9000:9000
    volumes:
      - /var/www/html
      - ${CONTENT_DIR}:/var/www/html/wp-content/
      - ${TEMP_DIR:-~/tmp/WordPress}:/tmp/WordPress:rw
    networks:
      - wp_deploy
    depends_on:
      - db
