kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: wordpress-backup-config
  annotations:
    openshift.io/display-name:  Cron job templates for backups.
    description: Cron job templates for backups.
    tags: backups,wordpress

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "mariadb-backup"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "23576a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: POOL_NAME
    displayName: "Pool name"
    description: "The database shared pool instance."
    required: true
    value: "pool"
  - name: BACKUP_CONFIG
    displayName: "Backup config"
    description: "The backup config."
    required: false
    value: ""

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-file-config--${POOL_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "${ROLE_NAME} file configuration"
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-file-config--${POOL_NAME}
        app: ${APP_NAME}
        env: ${ENV_NAME}
    data:
      backup.conf: ${BACKUP_CONFIG}