apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb
spec:
  resources:
    requests:
      storage: 500M
  storageClassName: netapp-block-standard

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress
  namespace: default
spec:
  resources:
    requests:
      storage: 500M
  storageClassName: netapp-file-standard

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress-nginx
spec:
  host: wp-dev.apps.silver.devops.gov.bc.ca
  to:
    name: dev--wordpress-nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"wordpress-wordpress-run:dev","namespace":
      "23576a-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"wordpress-wordpress--dev\")].image"},{"from":{"kind":"ImageStreamTag","name":"wordpress-nginx-run:dev","namespace":
      "23576a-tools"},"fieldPath":"spec.template.spec.containers[?(@.name==\"wordpress-nginx--dev\")].image"}]'
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: webserver
    app.kubernetes.io/part-of: wordpress
    app.openshift.io/runtime: nginx
  name: wordpress
  namespace: default
spec:
  selector:
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        net-tcp-8080: server
        net-tcp-9000: client
    spec:
      containers:
      - name: wordpress-core
        image: image-registry.openshift-image-registry.svc:5000/23576a-tools/wordpress-wordpress-run:dev
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
      - name: wordpress-nginx
        image: image-registry.openshift-image-registry.svc:5000/23576a-tools/wordpress-nginx-run:dev
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      triggers:
      - type: ConfigChange

