apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- volumes.yaml
- deployment.yaml
namespace: default
configMapGenerator:
- name: wordpress-config-env-config--dev
  literals:
  - MYSQL_DATABASE=dev_dev
  - WORDPRESS_DB_HOST=wordpress-mariadb--dev
  - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/WORDPRESS_DB_PASSWORD
