apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- volumes.yaml
- services.yaml
- deployment.yaml

namespace: default
commonLabels:
  app: wordpress
  site: local
  pool: default
  env: local
configMapGenerator:
- name: wordpress-config
  literals:
  - MYSQL_DATABASE=dev_dev
  - WORDPRESS_DB_HOST=wordpress-mariadb--dev
  - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/WORDPRESS_DB_PASSWORD
secretGenerator:
- name: wordpress-secrets
  type: Opaque
  literals:
  - MYSQL_PASSWORD=mysqlpassword
  - MYSQL_ROOT_PASSWORD=rootmysqlpassword

