apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods.
  labels:
    app: wordpress
    env: dev
    name: wordpress-mariadb--dev
    role: mariadb
    site: dev
  name: wordpress-mariadb--dev
  namespace: 23576a-dev
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
    env: dev
    name: wordpress-mariadb--dev
    role: mariadb
    site: dev
  sessionAffinity: None
  type: ClusterIP
