apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Exposes and load balances the application pods.
  labels:
    name: wordpress-mariadb
    role: mariadb
  name: wordpress-mariadb
  namespace: default
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: wordpress-mariadb
    role: mariadb
  sessionAffinity: None
  type: ClusterIP
