apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb--dev
  namespace: 23576a-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M
  storageClassName: netapp-block-standard
  volumeMode: Filesystem