apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb--dev
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  storageClassName: local-storage
  volumeMode: Filesystem