apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb--dev
  namespace: default
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50M
  