kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: wordpress-php-fpm-configuration
  annotations:
    openshift.io/display-name:  Configuration templates for the persistent storage (classic) version of the WordPress deploy.
    description: Configuration templates for the persistent storage (classic) version of the WordPress deploy.
    tags: php-fpm,wordpress

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "php-fpm"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "23576a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: SITE_NAME
    displayName: "Site name"
    description: "The name for the site (a-zA-Z_)"
    required: true
    value: "global"
  - name: POOL_NAME
    displayName: "Pool name"
    description: "The database shared pool instance."
    required: true
    value: "pool"
  - name: MAX_FILE_SIZE
    displayName: "The max file size for upload"
    value: "512M"

  - name: APP_DOMAIN
    displayName: "Application Hostname"
    description: "The exposed hostname that will route to the the application."
    value: "wp-dev.apps.silver.devops.gov.bc.ca"
  - name: WORDPRESS_DB_HOST
    displayName: "WORDPRESS_DB_HOST"
    description: "Database server hostname."
    value: "wordpress-mariadb"
  - name: WORDPRESS_MULTISITE
    displayName: "WORDPRESS_MULTISITE"
    description: "Set to 1 to enable multisite, 0 to disable.  IMPORTANT, it has to be 0 for initial setup."
    required: true
    value: ""

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-env-config--${SITE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "php-fpm env configuration"
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-env-config--${SITE_NAME}
        app: ${APP_NAME}
        env: ${ENV_NAME}
        site: ${SITE_NAME}
    type: Opaque
    data:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}--${SITE_NAME}
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/WORDPRESS_DB_PASSWORD
      WORDPRESS_ALLOW_MULTISITE: "${WORDPRESS_MULTISITE}"
      WORDPRESS_MULTISITE: "${WORDPRESS_MULTISITE}"
      WORDPRESS_SUBDOMAIN_INSTALL: "0"
      WORDPRESS_DOMAIN_CURRENT_SITE: "${APP_DOMAIN}"
      WORDPRESS_PATH_CURRENT_SITE: "/"
      WORDPRESS_SITE_ID_CURRENT_SITE: "1"
      WORDPRESS_BLOG_ID_CURRENT_SITE: "1"
      WORDPRESS_CONFIG_EXTRA: |
        /* Multisite */
        define( 'WP_ALLOW_MULTISITE', true );
        define( 'MULTISITE', !!filter_var( getenv_docker( 'WORDPRESS_MULTISITE', '0' ), FILTER_VALIDATE_BOOLEAN ) );
        define( 'SUBDOMAIN_INSTALL', false );
        define( 'DOMAIN_CURRENT_SITE', '${APP_DOMAIN}' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', intval( getenv_docker( 'WORDPRESS_SITE_ID_CURRENT_SITE', '1' ) ) );
        define( 'BLOG_ID_CURRENT_SITE', intval( getenv_docker( 'WORDPRESS_SITE_ID_CURRENT_SITE', '1' ) ) );
        /* For Active Directory Integration on Multisite. */
        define( 'IS_WPMU', true );
        /* Other configs */
        define( 'WP_DEBUG_LOG', false );
      # Using the _FILE uses secret from secret file via getenv_docker function https://github.com/docker-library/wordpress/blob/master/wp-config-docker.php#L30
      WORDPRESS_AUTH_KEY_FILE: /run/secrets/wordpress/WORDPRESS_AUTH_KEY
      WORDPRESS_AUTH_SALT_FILE: /run/secrets/wordpress/WORDPRESS_AUTH_SALT
      WORDPRESS_LOGGED_IN_KEY_FILE: /run/secrets/wordpress/WORDPRESS_LOGGED_IN_KEY
      WORDPRESS_LOGGED_IN_SALT_FILE: /run/secrets/wordpress/WORDPRESS_LOGGED_IN_SALT
      WORDPRESS_NONCE_KEY_FILE: /run/secrets/wordpress/WORDPRESS_NONCE_KEY
      WORDPRESS_NONCE_SALT_FILE: /run/secrets/wordpress/WORDPRESS_NONCE_SALT
      WORDPRESS_SECURE_AUTH_KEY_FILE: /run/secrets/wordpress/WORDPRESS_SECURE_AUTH_KEY
      WORDPRESS_SECURE_AUTH_SALT_FILE: /run/secrets/wordpress/WORDPRESS_SECURE_AUTH_SALT
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-file-config--${SITE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "php-fpm file configuration"
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-file-config--${SITE_NAME}
        app: ${APP_NAME}
        env: ${ENV_NAME}
        site: ${SITE_NAME}
    type: Opaque
    data:
      app.ini: |-
        upload_max_filesize=${MAX_FILE_SIZE}
        post_max_size=${MAX_FILE_SIZE}
        memory_limit=256M
        max_execution_time=300
        max_input_time=300